# Generated by Django 5.0.6 on 2024-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataOnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Назва сторінки')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текстові дані на сторінці',
                'verbose_name_plural': 'Текстові дані на сторінці',
                'db_table': 'Текстові дані на сторінці',
            },
        ),
    ]
